// JoypadCode.h

#pragma once

typedef enum JoypadIDTag {
    INPUT_PAD1 = JOYSTICKID1,
    INPUT_PAD2 = JOYSTICKID2
} JoypadID;

typedef enum JoypadCodeTag {
    PAD_INPUT_1 = JOY_BUTTON1,
    PAD_INPUT_2 = JOY_BUTTON2,
    PAD_INPUT_3 = JOY_BUTTON3,
    PAD_INPUT_4 = JOY_BUTTON4,
    PAD_INPUT_5 = JOY_BUTTON5,
    PAD_INPUT_6 = JOY_BUTTON6,
    PAD_INPUT_7 = JOY_BUTTON7,
    PAD_INPUT_8 = JOY_BUTTON8,
    PAD_INPUT_9 = JOY_BUTTON9,
    PAD_INPUT_10 = JOY_BUTTON10,
    PAD_INPUT_11 = JOY_BUTTON11,
    PAD_INPUT_12 = JOY_BUTTON12,
    PAD_INPUT_13 = JOY_BUTTON13,
    PAD_INPUT_14 = JOY_BUTTON14,
    PAD_INPUT_15 = JOY_BUTTON15,
    PAD_INPUT_16 = JOY_BUTTON16,
    PAD_INPUT_17 = JOY_BUTTON17,
    PAD_INPUT_18 = JOY_BUTTON18,
    PAD_INPUT_19 = JOY_BUTTON19,
    PAD_INPUT_20 = JOY_BUTTON20,
    PAD_INPUT_21 = JOY_BUTTON21,
    PAD_INPUT_22 = JOY_BUTTON22,
    PAD_INPUT_23 = JOY_BUTTON23,
    PAD_INPUT_24 = JOY_BUTTON24,
    PAD_INPUT_25 = JOY_BUTTON25,
    PAD_INPUT_26 = JOY_BUTTON26,
    PAD_INPUT_27 = JOY_BUTTON27,
    PAD_INPUT_28 = JOY_BUTTON28,
    PAD_INPUT_UP = JOY_BUTTON29,
    PAD_INPUT_DOWN = JOY_BUTTON30,
    PAD_INPUT_LEFT = JOY_BUTTON31,
    PAD_INPUT_RIGHT = JOY_BUTTON32,
} JoypadCode;
