// JoypadButton.h

#pragma once

// Joypad 識別番号
typedef enum JoypadIDTag {
    JOYPAD_1 = JOYSTICKID1,
    JOYPAD_2 = JOYSTICKID2
} JoypadID;

// Joypad ボタン識別番号
typedef enum JoypadButtonTag {
    JOYPAD_BUTTON_1 = JOY_BUTTON1,
    JOYPAD_BUTTON_2 = JOY_BUTTON2,
    JOYPAD_BUTTON_3 = JOY_BUTTON3,
    JOYPAD_BUTTON_4 = JOY_BUTTON4,
    JOYPAD_BUTTON_5 = JOY_BUTTON5,
    JOYPAD_BUTTON_6 = JOY_BUTTON6,
    JOYPAD_BUTTON_7 = JOY_BUTTON7,
    JOYPAD_BUTTON_8 = JOY_BUTTON8,
    JOYPAD_BUTTON_9 = JOY_BUTTON9,
    JOYPAD_BUTTON_10 = JOY_BUTTON10,
    JOYPAD_BUTTON_11 = JOY_BUTTON11,
    JOYPAD_BUTTON_12 = JOY_BUTTON12,
    JOYPAD_BUTTON_13 = JOY_BUTTON13,
    JOYPAD_BUTTON_14 = JOY_BUTTON14,
    JOYPAD_BUTTON_15 = JOY_BUTTON15,
    JOYPAD_BUTTON_16 = JOY_BUTTON16,
    JOYPAD_BUTTON_17 = JOY_BUTTON17,
    JOYPAD_BUTTON_18 = JOY_BUTTON18,
    JOYPAD_BUTTON_19 = JOY_BUTTON19,
    JOYPAD_BUTTON_20 = JOY_BUTTON20,
    JOYPAD_BUTTON_21 = JOY_BUTTON21,
    JOYPAD_BUTTON_22 = JOY_BUTTON22,
    JOYPAD_BUTTON_23 = JOY_BUTTON23,
    JOYPAD_BUTTON_24 = JOY_BUTTON24,
    JOYPAD_BUTTON_25 = JOY_BUTTON25,
    JOYPAD_BUTTON_26 = JOY_BUTTON26,
    JOYPAD_BUTTON_27 = JOY_BUTTON27,
    JOYPAD_BUTTON_28 = JOY_BUTTON28,
    JOYPAD_BUTTON_UP = JOY_BUTTON29, // アナログパッド上
    JOYPAD_BUTTON_DOWN = JOY_BUTTON30, // アナログパッド下
    JOYPAD_BUTTON_LEFT = JOY_BUTTON31, // アナログパッド左
    JOYPAD_BUTTON_RIGHT = JOY_BUTTON32, // アナログパッド右
} JoypadButton;
